### PR TITLE
fix: make sure that our concurrency check ignore packages without task

### LINKED ISSUE #4291: [WEB-880] [turborepo] Persistent task concurrency validation not taking into account whether package has the script defined
### What version of Turborepo are you using?

1.8.5

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I believe this is related to #4205.  If you have a task which is designated as `persistent`, it will validate that concurrency limits are not breached.  However, the calculation of how many parallel tasks will be executed is not taking into account that not every package in the defined filter has the script defined.

For instance, I have a turbo task `dev` which is flagged as persistent.  This is launched as:
`turbo run dev --filter=@scope/app.*...`

The count of tasks gets indicated as 24 in my example, which breaches the concurrency limit of 10.  The count of 24 is the total count of packages matching the filter and all of its dependencies.  However, only 4 of the packages in the filter's scope actually have `dev` scripts defined.  This same issue does not occur if a filter is not defined.  Effectively, the validation of concurrency limits should verify if a package in the filter's scope actually has the script defined before erroring.  Packages without the script defined should not be counted in the validation.

### Expected Behavior

Since in my example only 4 `dev` scripts exist within the filter's scope, the turbo task should be permitted to run as it will not breach concurrency limits.

### To Reproduce

* Create a workspace with 2 packages -- `a` and `b`
  * Make `b` a dependency of `a`
* Define a `persistent` turbo task (e.g. `dev`) in `turbo.json`
* Add a script to package `a` matching the persistent task's name
* Execute `turbo run <task_name> --filter=a... --concurrency=1`

In this example, only package `a` will run a script because it's the only one with the script defined.  However, the count will be detected as exceeding the limit of 1 parallel task because it's using a count of all packages in scope and not the number of scripts which will be executed.

### Reproduction Repo

_No response_

<sub>[WEB-880](https://linear.app/vercel/issue/WEB-880/[turborepo]-persistent-task-concurrency-validation-not-taking-into)</sub>

<sub>[TURBO-1141](https://linear.app/vercel/issue/TURBO-1141/[web-880]-[turborepo]-persistent-task-concurrency-validation-not)</sub>

### PR DESCRIPTION
**Pull request by arlyon**
### Description

Closes #4291

The validation check to ensure the persistent task count doesn't exceed concurrency did not check if the package actually contained a particular task, leading to erroneous validation when running persistent tasks if you have more than N packages in the project.

Closes TURBO-1914

### CODE REVIEW

File: crates/turborepo-lib/src/engine/mod.rs [hunk 1]
```diff
@@ -201,7 +197,19 @@ impl Engine<Built> {
                     }
                 }
 
-                Ok(is_persistent)
+                // check if the package for the task has that task in its package.json
+                let info = package_graph
+                    .workspace_info(&WorkspaceName::Other(task_id.package().to_string()))
```
Comment (chris-olszewski) [inline crates/turborepo-lib/src/engine/mod.rs:202]: I'm assuming this is what's causing the crashes. `WorkspaceName::from` handles `//` correctly and maps it to `WorkspaceName::Root`
```suggestion
                    .workspace_info(&WorkspaceName::from(task_id.package().to_string()))
```

File: crates/turborepo-lib/src/engine/mod.rs [hunk 2]
```diff
@@ -201,7 +197,19 @@ impl Engine<Built> {
...
+                    .expect("package graph should contain workspace info for task package");
+
+                let package_has_task = info.package_json.scripts.contains_key(task_id.task());
```
Comment (chris-olszewski) [inline crates/turborepo-lib/src/engine/mod.rs:205]: In order to match what we do other places to match Go behavior I think we need to also treat `""` as a package not having a task.
```suggestion
                let package_has_task = info.package_json.scripts.get(task_id.task()).map_or(false, |script| !script.is_empty());
```

**Review by chris-olszewski — CHANGES_REQUESTED** [review]
It would be great to have a test for these changes.

It's also worth noting that this introduces intentionally divergent behavior between Rust/Go. Not saying that updating Go is necessary since we're deleting it in a ~month, but might affect testing strategy.

**Review by mehulkar — COMMENTED** [review]
Change looks good, but a test case would be great (IMO unit test would be fine in this case if that's possible)

File: crates/turborepo-lib/src/engine/mod.rs (hunk 1 above)
Comment (arlyon) [reply crates/turborepo-lib/src/engine/mod.rs:202]: TY

File: crates/turborepo-lib/src/engine/mod.rs [hunk 3]
```diff
@@ -260,3 +273,112 @@ impl fmt::Display for TaskNode {
...
+        }
+
+        let engine = engine.seal();
+        let current_dir = std::env::current_dir().unwrap();
+
+        let mut graph_builder = PackageGraph::builder(
+            AbsoluteSystemPath::from_std_path(&current_dir).unwrap(),
+            PackageJson::default(),
+        )
+        .with_package_discovery(DummyDiscovery(&tmp));
```
Comment (chris-olszewski) [inline crates/turborepo-lib/src/engine/mod.rs:371]: I think we could avoid providing valid paths and writing to the FS by using builder methods like we do [here](https://github.com/vercel/turbo/blob/main/crates/turborepo-repository/src/package_graph/mod.rs#L695). I think this would avoid the test failures for Windows.

**Review by chris-olszewski — APPROVED** [review]
Approving. Just need to update the integration tests with a lower the concurrency limit now that we're checking for N instead of N+1.

Also get the Windows rust test to pass, probably easiest way is to avoid actual FS work completely instead of trying to figure out traversals between drives.
