### PR TITLE
fix(turborepo): factor in negated globs for workspace detection in codemods

### LINKED ISSUE #8327: `npx @turbo/codemod migrate` alters `package.json` for packages excluded in `pnpm-workspace.yaml`
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

I do not have one

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

`@turbo/codemod@2.0.0-canary.4`

### Describe the Bug

`Running add-package-names` modifies folders that are listed as ignored in `pnpm-workspace.yaml`

```yaml
packages:
  - '!**/_isolated_/**'
```

### Expected Behavior

Should not touch those `package.json`s

### To Reproduce

`npx @turbo/codemod@canary migrate`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NicholasLYang**
### Description

Closes #8327. We now factor in negated globs

### Testing Instructions

Added a test to `add-package-name` migration that ensures we ignore package covered by negated glob

### CODE REVIEW

File: packages/turbo-workspaces/src/getWorkspaceDetails.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
+import { Workspace } from "@turbo/repository";
```
Comment (mehulkar) [inline packages/turbo-workspaces/src/getWorkspaceDetails.ts:1]: - I don't see this being used, is it a mistaken import?
- was this already in turbo-workspaces package.json?
- If not, `@turbo/repository` has native dependencies, so anyone using `@turbo/workspaces` will now get hit with a "supported platforms" issue if they aren't one one.

Comment (NicholasLYang) [reply packages/turbo-workspaces/src/getWorkspaceDetails.ts:1]: Ah yeah that made it in by mistake

**Review by chris-olszewski — APPROVED** [review]
