### PR TITLE
Fix getting workspace ignores in case of non-monorepo

### LINKED ISSUE #4140: [turborepo] Configuring globalDependencies in a non-monorepo
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I tried to add turborepo to an existing non-monorepo next project.
The `turbo.json` configuration is as follows:
```json
{
  "$schema": "https://turbo.build/schema.json",
  "globalDependencies": ["**/.env.*local"],
  "pipeline": {
    "build": {
      "outputs": [".next/**"]
    },
    "lint": {},
    "dev": {
      "cache": false,
      "persistent": true
    }
  }
}
```

But when I run
```bash
yarn turbo build
```
I get the following error:

> run failed: failed to collect global hash inputs: package.json: no workspaces found. Turborepo requires Yarn workspaces to be defined in the root package.json
> Turbo error: failed to collect global hash inputs: package.json: no workspaces found. Turborepo requires Yarn workspaces to be defined in the root package.json
> error Command failed with exit code 1.

If I remove
```json
"globalDependencies": ["**/.env.*local"],
```
from the configuration, seems to work instead.

I tried to do the same with the official example of [non-monorepo](https://github.com/vercel/turbo/tree/main/examples/non-monorepo) and the same error occurs.

### Expected Behavior

Being able to use turborepo in a 'non-monorepo' by having the configuration option `globalDependencies` working.

### To Reproduce

* Install [Turborepo non-monorepo starter](https://github.com/vercel/turbo/tree/main/examples/non-monorepo) :

```bash
npx degit vercel/turbo/examples/non-monorepo non-monorepo
cd non-monorepo
yarn
git init . && git add . && git commit -m "Init"
```

* Edit the file `turbo.json` by adding the option `"globalDependencies": ["**/.env.*local"]`.

* Run:
```bash
yarn turbo build
```

### Reproduction Repo

_No response_

### PR DESCRIPTION
**Pull request by stefanofa**
### Description

Hey @mehulkar I tried to fix #4140 .
This is my first time reading or writing in go so it's likely I may have done something wrong.

The way I did it is a bit redundant, as in the case of a monorepo the call to `getWorkspaceGlobs` is made 2 times and so is not the most efficient. Unfortunately I think I lack a lot of context to try and come up with a better solution, but I felt like trying :)

### CODE REVIEW

**Review by mehulkar — COMMENTED** [review]
Hey! thanks for taking a stab at this!

> The way I did it is a bit redundant, as in the case of a monorepo the call to `getWorkspaceGlobs` is made 2 times and so is not the most efficient. 

Just making sure, do you mean there's a duplicate call to `fs.ReadPackageJSON`?

Instead of `fs.ReadPackageJSON` twice, how about returning a custom error from `getWorkspaceGlobs` (instead of `fmt.Errorf()`), and returning the `ignores: ["node_modules/**]` in that case, but bubbling up all other errors?

Happy to give you another pointer to custom error handling if you want! 

PS, I know @tknickman also said he might have time to take a look at this, in case he had a different solution in mind.

**Comment by stefanofa** [comment]
> Just making sure, do you mean there's a duplicate call to fs.ReadPackageJSON?

Yes, that's what I meant.

By the way, I tried the refactor you suggested!

File: cli/internal/packagemanager/yarn.go [hunk 1]
```diff
@@ -42,6 +48,13 @@ var nodejsYarn = PackageManager{
 
 		globs, err := pm.getWorkspaceGlobs(rootpath)
 		if err != nil {
+			// In case of a non-monorepo, the workspaces field is empty and only node_modules in the root should be ignored
+			_, ok := err.(*NoWorkspacesFoundError)
+			if ok {
```
Comment (mehulkar) [inline cli/internal/packagemanager/yarn.go:53]: you can use `errors.As()` here instead of coercing the type. Example from another part of the codebase:
https://github.com/vercel/turbo/blob/6bc8b5e0bdf920e799ca693bf697acdf0796640b/cli/internal/core/engine.go#L183-L193

File: cli/internal/packagemanager/yarn.go [hunk 2]
```diff
@@ -42,6 +48,13 @@ var nodejsYarn = PackageManager{
...
+				ignores := make([]string, 1)
+				ignores[0] = "node_modules/**"
+				return ignores, nil
```
Comment (mehulkar) [inline cli/internal/packagemanager/yarn.go:56]:
```suggestion
				return []string{"node_modules/**"}, nil
```

(I'm not a Go expert here, but this reads a bit cleaner to me. I'm not sure if the size allocation is implicit when declaring with literal values, or if your `make` with size is better. cc @chris-olszewski

**Review by mehulkar — COMMENTED** [review]
Couple more questions:

- What happens in a real monorepo when the workspace config is missing?
- In `npm` and `pnpm` implementations of `getWorkspaceIgnores`, the default return value is `**/node_modules/**`. Should we use that as the default here also? Or can we trust the user that if the workspaces config is missing, then we really only want to ignore the root `./node_modules`?

**Comment by chris-olszewski** [comment]
> What happens in a real monorepo when the workspace config is missing?

This should still error as we call `packageManager.GetWorkspaces` in the `BuildPackageGraph` context constructor.

>     * In `npm` and `pnpm` implementations of `getWorkspaceIgnores`, the default return value is `**/node_modules/**`. Should we use that as the default here also? Or can we trust the user that if the workspaces config is missing, then we really only want to ignore the root `./node_modules`?


I think from my groking that `node_modules/**` matches what yarn does by default: https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/config.js#L816

**Comment by mehulkar** [comment]
Let's merge this into my branch then!
