### PR TITLE
filter out invalid Pipelines from TurboJSON when running turbo prune

### LINKED ISSUE #1161: Unable to run command when package#task defined `turbo.json` is missing
### What version of Turborepo are you using?

1.26.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

If you have _manually_ 'pruned' your monorepo so that it only includes the packages that are used by the target project and try to run a command such as `turbo run build` then it can fail when the `turbo.json` file defined a task, such as:

```json
    "webapp#build": {
      "outputs": [".next/**", "dist/**", "public/dist/**"],
      "dependsOn": ["webapp#prebuild", "^build"]
    }
```

The `webapp`-package is not included in the _pruned_ mono repo the `turbo` command fails with an error like:

```bash
Error preparing engine: found reference to unknown package: webapp in task webapp#prebuild
```

### Expected Behavior

Able to execute commands which don't depend on missing packages

### To Reproduce

Working on this

### PR DESCRIPTION
**Pull request by arlyon**
Closes #1161

This is based on top of https://github.com/vercel/turbo/pull/3213

Open questions:

- do we want to include root-scoped tasks in the output?
- what should the permissions be on the new turbo file created? we could read the permissions from the old one, or set it manually (I currently do 0664)

### CODE REVIEW

File: cli/internal/fs/turbo_json.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ type rawTurboJSON struct {
 	GlobalEnv []string `json:"globalEnv,omitempty"`
 	// Pipeline is a map of Turbo pipeline entries which define the task graph
 	// and cache behavior on a per task or per package-task basis.
-	Pipeline Pipeline
```
Comment (arlyon) [inline cli/internal/fs/turbo_json.go:31]: Is there a reason this was omitted?

File: cli/internal/fs/turbo_json.go [hunk 2]
```diff
@@ -347,3 +347,15 @@ func (c *TurboJSON) UnmarshalJSON(data []byte) error {
 
 	return nil
 }
+
+// MarshalJSON converts a TurboJSON into the equivalent json object in bytes
+// note: we go via rawTurboJSON so that the output format is correct
+func (c *TurboJSON) MarshalJSON() ([]byte, error) {
```
Comment (arlyon) [inline cli/internal/fs/turbo_json.go:353]: If we Marshal the TurboJSON directly, the naming on the fields is incorrect (PascalCase)

File: cli/scripts/e2e/e2e.ts [hunk 3]
```diff
@@ -48,7 +48,21 @@ for (let npmClient of ["yarn", "berry", "pnpm6", "pnpm", "npm"] as const) {
   const Suite = uvu.suite(`${npmClient}`);
 
   const repo = new Monorepo("basics");
-  repo.init(npmClient, basicPipeline);
+  repo.init(npmClient, {
+    pipeline: {
```
Comment (arlyon) [inline cli/scripts/e2e/e2e.ts:52]: There is maybe a better place to do this.

File: cli/internal/fs/turbo_json.go (hunk 1 above)
Comment (nathanhammond) [reply cli/internal/fs/turbo_json.go:31]: Not that I'm aware of. Seems good! 👍

File: cli/internal/prune/prune.go [hunk 4]
```diff
@@ -191,7 +193,34 @@ func (p *prune) prune(opts *turbostate.PrunePayload) error {
 	}
 
 	if fs.FileExists("turbo.json") {
-		if err := fs.CopyFile(&fs.LstatCachedFile{Path: p.base.RepoRoot.UntypedJoin("turbo.json")}, fullDir.UntypedJoin("turbo.json").ToStringDuringMigration()); err != nil {
+		turboJSON, err := fs.ReadTurboConfig(".", rootPackageJSON)
```
Comment (nathanhammond) [inline cli/internal/prune/prune.go:196]: We should drop the `fs.FileExists` condition:
1. It has implicit cwd behavior.
2. We can just try to read, handle any error, and reduce syscalls as a consequence. (This will also make sure we have a viable error API for `ReadTurboConfig`.)

(If you want to pick off the same thing for `.gitignore` above that'd also be good.)

Also, 
```suggestion
		turboJSON, err := fs.ReadTurboConfig(p.base.RepoRoot, rootPackageJSON)
```

"." is accidentally abusing the fact that primitives don't get typechecked on the way in to the `ReadTurboConfig` call.

File: cli/internal/prune/prune.go [hunk 5]
```diff
@@ -191,7 +193,34 @@ func (p *prune) prune(opts *turbostate.PrunePayload) error {
...
+			}
+		}
+
+		bytes, err := turboJSON.MarshalJSON()
+
+		if err != nil {
+			return errors.Wrap(err, "failed to write turbo.json")
+		}
+
+		if err := os.WriteFile(fullDir.UntypedJoin("turbo.json").ToStringDuringMigration(), bytes, 0644); err != nil {
```
Comment (nathanhammond) [inline cli/internal/prune/prune.go:223]: Coding in GitHub comments, but I think this works:
```suggestion
		if err := fullDir.UntypedJoin("turbo.json").WriteFile(bytes, 0644); err != nil {
```

File: cli/internal/prune/prune.go [hunk 6]
```diff
@@ -191,7 +193,34 @@ func (p *prune) prune(opts *turbostate.PrunePayload) error {
...
 			return errors.Wrap(err, "failed to copy root turbo.json")
```
Comment (nathanhammond) [inline cli/internal/prune/prune.go:224]: Optional:
```suggestion
			return errors.Wrap(err, "failed to write turbo.json")
```

File: cli/scripts/e2e/e2e.ts (hunk 3 above)
Comment (nathanhammond) [reply cli/scripts/e2e/e2e.ts:52]: This would be fine, but I'm going to ask for enough bonus tests that you're gonna want a `prunePipeline` constant. 😜

Comment (nathanhammond) [inline cli/scripts/e2e/e2e.ts:52]: Bonus test cases!

I'm trying to see what happens to the dependency graph construction when you feed it possibly-surprising input where `dependsOn` eventually contains a task that got pruned. (Not sure if this will reveal a bug in `prune` or not. 😜)

- `"#build"` (empty package name).
- Task with a `dependsOn` with a fully-qualified task id like `"c#build"` that is supposed to get pruned. 
- Task in the `dependsOn` which transitively depends on `c#build`. (AKA: do we need to build the whole graph in order to prune?)

**Review by nathanhammond — CHANGES_REQUESTED** [review]
Here's some notes!

File: cli/internal/util/task_id.go [hunk 7]
```diff
@@ -41,6 +41,16 @@ func IsPackageTask(task string) bool {
 	return strings.Contains(task, TaskDelimiter)
 }
 
+// IsTaskInPackage returns true if the task does not belong to a different package
+// note that this means unscoped tasks will always return true
+func IsTaskInPackage(task string, packageName string) bool {
```
[the remark this answers is not in the document]
Comment (arlyon) [reply cli/internal/util/task_id.go:46]: Do we want to change the singnature so that it may error out?

File: cli/internal/prune/prune.go (hunk 5 above)
Comment (arlyon) [reply cli/internal/prune/prune.go:223]: It does indeed, thank you!

File: cli/scripts/e2e/e2e.ts (hunk 3 above)
Comment (arlyon) [reply cli/scripts/e2e/e2e.ts:52]: Upon some deeper thought, I think you are right and we will need to walk the graph. I will chalk it up to learning the codebase 😅. For whatever reason I assumed that leaving only the 'entry' packages in the turbo json would be enough but I can see now that that is not the case. I am adding a few tests and will have a new revision by the time you are up tomorrow.

File: cli/internal/util/task_id.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (nathanhammond) [reply cli/internal/util/task_id.go:46]: Nah, we can just flip the boolean for the `""` case. It's not a valid state, so I don't care too much about validating the input as long as the output is reasonable.

File: cli/internal/prune/prune.go [hunk 8]
```diff
@@ -184,15 +185,44 @@ func (p *prune) prune(opts *turbostate.PrunePayload) error {
 		return errors.Wrap(err, "Failed to flush pruned lockfile")
 	}
 
-	if fs.FileExists(".gitignore") {
-		if err := fs.CopyFile(&fs.LstatCachedFile{Path: p.base.RepoRoot.UntypedJoin(".gitignore")}, fullDir.UntypedJoin(".gitignore").ToStringDuringMigration()); err != nil {
-			return errors.Wrap(err, "failed to copy root .gitignore")
-		}
+	// to reduce syscalls we just try to copy immediately. if it fails
+	// when getting mode, then continue because the file doesn't exist
+	err = fs.CopyFile(&fs.LstatCachedFile{Path: p.base.RepoRoot.UntypedJoin(".gitignore")}, fullDir.UntypedJoin(".gitignore").ToStringDuringMigration())
```
Comment (nathanhammond) [inline cli/internal/prune/prune.go:190]: Aside: I'd love to get `CopyFile` into a better place (not that it makes any sense to do this pre-Rust). At this point it's _only_ used in `prune`, and one teeny tiny place in `run_state.go`.

This used to be an important code path (enough so that `LstatCachedFile` as a perf optimization was worth it), but cache-to-tar has made it irrelevant.

File: cli/internal/prune/prune.go [hunk 9]
```diff
@@ -184,15 +185,44 @@ func (p *prune) prune(opts *turbostate.PrunePayload) error {
...
+	if err != nil && !strings.Contains(err.Error(), "getting mode") {
+		return errors.Wrap(err, "failed to copy root .gitignore")
+	}
```
[the remark this answers is not in the document]
Comment (arlyon) [reply cli/internal/prune/prune.go:193]: I think for the turbo.json that makes sense, but surely we don't want `prune` to require a `.gitignore` file to complete?

[the remark this answers is not in the document]
Comment (tknickman) [reply cli/internal/prune/prune.go]: Agreed, `.gitignore` shouldn't be required here

**Review by tknickman — APPROVED** [review]
One note about the requirement for .gitignore, bother otherwise lgtm
