### PR TITLE
fix inconsistent sys_path leading to watching issue on root dir

### LINKED ISSUE #3215: [turbopack] postcss config update needs deleting of .next folder
### What version of Turbopack are you using?

next.js 13.1.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

If I update `postcss.config.js`, nothing happens, until I `rm -rf .next`.

### Expected Behavior

It should update the config.

### To Reproduce

1. create-next-app
2. add postcss.config.js
3. build
4. modify the config with something wrong
5. build

### Reproduction Repo

_No response_

### PR DESCRIPTION
**Pull request by sokra**
It fixes the case when adding, removing or renaming files on root dir doesn't trigger an update.

maybe fixes #3215, but I can confirm as I can't really reproduce with the steps provided.

### CODE REVIEW

File: crates/turbo-tasks-fs/src/lib.rs [hunk 1]
```diff
@@ -264,8 +264,13 @@ impl DiskFileSystem {
     }
 
     pub async fn to_sys_path(&self, fs_path: FileSystemPathVc) -> Result<PathBuf> {
-        let path = Path::new(&self.root).join(&*unix_to_sys(&fs_path.await?.path));
-        Ok(path)
+        let path = Path::new(&self.root);
+        if fs_path.await?.path.is_empty() {
+            Ok(path.to_path_buf())
+        } else {
+            let path = path.join(&*unix_to_sys(&fs_path.await?.path));
```
Comment (sokra) [inline crates/turbo-tasks-fs/src/lib.rs:271]: Joining an empty path leads to a tailing `/` which is not matching the path reported from watcher

File: crates/turbo-tasks-fs/src/lib.rs [hunk 2]
```diff
@@ -264,8 +264,13 @@ impl DiskFileSystem {
     }
 
     pub async fn to_sys_path(&self, fs_path: FileSystemPathVc) -> Result<PathBuf> {
-        let path = Path::new(&self.root).join(&*unix_to_sys(&fs_path.await?.path));
```
Comment (sokra) [inline crates/turbo-tasks-fs/src/lib.rs:267]: Joining an empty path leads to a tailing `/` which is not matching the path reported from watcher

File: crates/turbo-tasks-fs/src/lib.rs [hunk 3]
```diff
@@ -264,8 +264,12 @@ impl DiskFileSystem {
...
-        Ok(path)
+        let path = Path::new(&self.root);
+        Ok(if fs_path.await?.path.is_empty() {
+            path.to_path_buf()
+        } else {
+            path.join(&*unix_to_sys(&fs_path.await?.path))
```
Comment (alexkirsz) [inline crates/turbo-tasks-fs/src/lib.rs:271]: No need to .await this twice.

**Review by alexkirsz — APPROVED** [review]
