### PR TITLE
fix: added `LD_LIBRARY_PATH` to default forwarded env vars

### LINKED ISSUE #8411: Turbo does not forward `LD_LIBRARY_PATH` by default
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

hard to do

### What package manager are you using / does the bug impact?

Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

main

### Describe the Bug

Turbo v2 does not forward `LD_LIBRARY_PATH` by default, which breaks Node on my machine (Node is "installed" with [pkgx dev command](https://docs.pkgx.sh/using-dev/dev))

``` console
$ yarn turbo run build
• Packages in scope: ...
• Running build in 2 packages
• Remote caching disabled
┌ ...#build > cache miss, executing 66d3f08e30e78ed2 
│ /home/me/.pkgx/nodejs.org/v20.11.0/bin/node: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
│ command finished with error: command (/home/me/...) /tmp/xfs-4da40043/yarn run build exited (127)
└────>
 ERROR  run failed: command  exited (127)
error: Recipe `build` failed on line 8 with exit code 127
```

Adding `"globalPassThroughEnv": ["LD_LIBRARY_PATH"]` to the turbo.json file fixes the bug

### Expected Behavior

`LD_LIBRARY_PATH` should be added to the list of forwarded env vars

### To Reproduce

This requires as rather heavy env set up, which I'm not sure how to provide. I might give a shot at creating a docker container if a maintainer deems it necessary.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GauBen**
### Description

Fixes #8411

### Testing Instructions

Works on my machine:tm:

### CODE REVIEW

**Comment by GauBen** [comment]
This may not be Turbo's job to take care of my broken setup, but it would have made my v1 to v2 migration smoother

File: crates/turborepo-lib/src/task_hash.rs [hunk 1]
```diff
@@ -471,6 +471,7 @@ impl<'a> TaskHasher<'a> {
                         "PWD",
                         "CI",
                         "NODE_OPTIONS",
+                        "LD_LIBRARY_PATH",
```
Comment (chris-olszewski) [inline crates/turborepo-lib/src/task_hash.rs:474]:
```suggestion
                        "LD_LIBRARY_PATH",
                        "DYLD_FALLBACK_LIBRARY_PATH",
                        "LIBPATH",
```

**Review by chris-olszewski — APPROVED** [review]
LGTM
Only suggestion is to add some additional common library paths

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c2bd0e80d32c75eb60bc61c245bb869bd9f84312

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by GauBen** [comment]
Thanks for the quick review!
