### PR TITLE
fix(Turborepo): ignore working tree state for fixed git comparisons

### LINKED ISSUE #7818: Using --filter="...[<sha>...<sha>]"` take local changes into account
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/EWhite613/turbo-issue-cache/tree/test-change

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.13.0-canary.1

### Describe the Bug

`turbo` takes into account local file changes when doing `turbo run test --filter="...[origin/main...HEAD]"`

### Expected Behavior

Expect local files and changes to not be taken into account. Should only be the commit shas directly referenced

### To Reproduce

```
git clone git@github.com:EWhite613/turbo-issue-cache.git
cd turbo-issue-cache
git checkout test-change
```

Run `turbo run test --filter="...[origin/main...HEAD]"` twice.  Notice first time it correctly only executes `api:test`. Second time it runs `api:test` and `@repo/logger:test` due to local files outputted (which are not in filter command)

### Additional context

Noticed this on both latest and canary.

Makes it difficult to only execute only a PRs changes (have to ensure I clean everything in between commands)

## Workaround
Specify `inputs`.

But I notice if I do this, I would have to do this for all my commands. Since say I have the following
```
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "test": {
      "dependsOn": ["^compile"],
      "outputs": ["artifacts/logs/test/xml/test-reports/xunit_results.xml"]
    },
    "lint": {
      "dependsOn": ["^compile", "^lint"]
    },
    "compile": {
      "dependsOn": ["^prepublishOnly"],
      "inputs": ["src/**"],
      "outputs": ["**/*.d.ts"]
    }
  }
}
```
I now need to let my test command be specific with it's inputs as well cause it will also see `compile`'s output as a change.

### PR DESCRIPTION
**Pull request by gsoltis**
### Description

 - Ignore uncommitted changes when both ends of a git commit comparison are specified
 - Update our internal representation of git range comparisons to fix the "from" side, and make the "to" side optional.
 - Slightly change our git range parsing to allow for empty ranges so that we can give a slightly better error message

Fixes #7818

### Testing Instructions

Tests updated for new internal representation, also added new tests to specify that uncommitted changes are ignored when both sides of the comparison are fixed

Closes TURBO-2696

### CODE REVIEW

**Comment by gsoltis** [comment]
* **#7838** <a href="https://app.graphite.dev/github/pr/vercel/turbo/7838?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gsoltis and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: crates/turborepo-lib/src/run/scope/target_selector.rs [hunk 1]
```diff
@@ -141,26 +131,34 @@ impl FromStr for TargetSelector {
...
 
-            if let Some(commits_str) = inner_str {
-                if let Some((a, b)) = commits_str.split_once("...") {
-                    (a.to_string(), b.to_string())
-                } else {
-                    (commits_str.to_string(), String::new())
+            let git_range = if let Some((a, b)) = commits_str.split_once("...") {
+                GitRange {
+                    from_ref: a.to_string(),
+                    to_ref: Some(b.to_string()),
```
Comment (chris-olszewski) [inline crates/turborepo-lib/src/run/scope/target_selector.rs:147]: Do we need to check if `b` is empty? If I'm parsing the regex correctly I think it can be empty.

**Review by chris-olszewski — APPROVED** [review]
LGTM, one question about differentiating between a `None` vs `Some("")` to ref.

File: crates/turborepo-lib/src/run/scope/target_selector.rs (hunk 1 above)
Comment (gsoltis) [reply crates/turborepo-lib/src/run/scope/target_selector.rs:147]: Oh yeah, good idea. The validation story here has not been great...

**Comment by gsoltis** [comment]
### Merge activity

* **Mar 26, 1:58 PM EDT**: @gsoltis merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vercel/turbo/7838).
