### PR TITLE
Escape colons in globs before sending to the daemon

### LINKED ISSUE #6136: [turborepo] turbo outputs cache breaks on tasks with `:` in the name
### What version of Turborepo are you using?

1.10.15

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

For compat reasons with older workflows and to match other patterns in our monorepo we prefix our turbo commands with `turbo:` in our package.json scripts, eg we'd run `pnpm turbo turbo:build` to run our turbrepo-managed build scripts.

This worked fine on 1.10.14. After updating to 1.10.15 we're now seeing the following warn log:

```
@alto/eslint-plugin:turbo:build: Failed to mark outputs as cached for @alto/eslint-plugin#turbo:build: rpc error: code = InvalidArgument desc = failed to parse glob expression: libs/eslint-plugin/.turbo/turbo-turbo:build.log
```

the full output from the `pnpm turbo turbo:build` command is as follows:

```
❯ pnpm turbo turbo:build
• Packages in scope: @alto/eslint-plugin, [others redacted]
• Running turbo:build in 11 packages
• Remote caching disabled
@alto/eslint-plugin:turbo:build: Failed to mark outputs as cached for @alto/eslint-plugin#turbo:build: rpc error: code = InvalidArgument desc = failed to parse glob expression: libs/eslint-plugin/.turbo/turbo-turbo:build.log
@alto/eslint-plugin:turbo:build: cache hit, suppressing logs 7414b54f61b794e9
```

If we rename all of our commands to `turbo-build` instead of `turbo:build` then the warning goes away.

### Expected Behavior

Turbo can cache outputs for commands that include a `:` in the name.

### To Reproduce

1. Add a `:` to a turbo command name
2. see the log show up when you run the command

### Reproduction Repo

_No response_

<sub>[TURBO-1440](https://linear.app/vercel/issue/TURBO-1440/[turborepo]-turbo-outputs-cache-breaks-on-tasks-with-in-the-name)</sub>

### PR DESCRIPTION
**Pull request by gsoltis**
### Description

Fixes #6136 
 - Escaped `:` in globs sent to the daemon from the Go client from unix clients, and truncate filenames with `:` on windows due to [Alternate Data Stream](https://learn.microsoft.com/en-us/sysinternals/downloads/streams)
 - Dropped printed warning when we fail to use the daemon for something. It is entirely possible that filewatching will initially time out while getting set up. We don't need to warn on that, there's nothing the user can do, it may just take a while on a large repository.

Note for the future: this may not be the ideal location for converting the format of the globs. It should most likely happen earlier in the process and be tagged with glob source information.

### Testing Instructions

 - Adds a test of the formatting rules applied to globs

Closes TURBO-1441

### CODE REVIEW

File: cli/internal/daemonclient/daemonclient.go [hunk 1]
```diff
@@ -32,12 +34,32 @@ func New(client *connector.Client) *DaemonClient {
 	}
 }
 
+// formats a repo-relative glob to unix format with ':' characters handled.
+// On windows, ':' is an invalid path character, but you can, and Turborepo does,
+// read to and write from files that contain alternate data streams denoted by ':'.
+// In the case of windows and an alternate data stream, we want change notifications just
+// for the root file. Note that since ':' denotes a data stream for a _file_, it cannot
+// appear in a directory name. Thus, if we find one, we know it's in the filename.
+// See https://learn.microsoft.com/en-us/sysinternals/downloads/streams
```
Comment (chris-olszewski) [inline cli/internal/daemonclient/daemonclient.go:43]: I'm hoping you can't delete data streams from a file individually. i.e. Do we need to worry about the situation where `build:schema` and `build:types` point to the same log file, but only the `types` stream gets deleted and we miss it's removal since the file is still there?

**Review by chris-olszewski — APPROVED** [review]
TIL files have streams on windows.

File: cli/internal/daemonclient/daemonclient.go (hunk 1 above)
Comment (chris-olszewski) [reply cli/internal/daemonclient/daemonclient.go:43]: Based on the `-d` flag of [the CLI tool](https://learn.microsoft.com/en-us/sysinternals/downloads/streams#using-streams) I'm guessing the answer is yes. Obviously non-blocking, but fun.

Comment (gsoltis) [reply cli/internal/daemonclient/daemonclient.go:43]: You can delete individual streams, we get a modification event for the file, which is sufficient for our purposes.
