### PR TITLE
fix: support pnpm workspace path aliasing

### LINKED ISSUE #6744: Wrong dependent task gets run when using pnpm relative path reference (eg. `workspace:../path/to/dep`)
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/steveluscher/pnpm-alias-pathspec-repro.git

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.11.1-canary.0

### Describe the Bug

Imagine that you:

1. Alias a package to a relative path (eg. `"luigi": "workspace:../waluigi"`)
2. Another package in your workspace has the same name as the alias (`luigi`)

…then you run some turborepo task.

```shell
pnpm i
cd packages/app/
pnpm turbo hello
```

Turborepo will run the task in the wrong workspace package; the `hello` script from `luigi/package.json` runs.

### Expected Behavior

Since the dependency `luigi` is aliased to `workspace:../waluigi`, I would expect the `hello` script from `waluigi/package.json` to run.

### To Reproduce

Follow the README in https://github.com/steveluscher/pnpm-alias-pathspec-repro.git.

### Additional context

> [!NOTE]
> If you change the dependency in `app/package.json` from `"luigi": "workspace:../waluigi"` to `"luigi": "workspace:waluigi@*"` it works as expected.

<sub>[TURBO-1899](https://linear.app/vercel/issue/TURBO-1899/wrong-dependent-task-gets-run-when-using-pnpm-relative-path-reference)</sub>

### PR DESCRIPTION
**Pull request by chris-olszewski**
### Description

Fixes #6744 

I highly suggest reviewing each commit on it's own as the code move done in the first commit makes the cumulative diff hard to understand. I wanted to clean up this code a bit as we'll need to extend it further for supporting https://github.com/vercel/turbo/issues/7188

This adds support for the PNPM feature of [aliasing a package via path](https://pnpm.io/workspaces#referencing-workspace-packages-through-their-relative-path). 

The slightly tricky part of this is that there are many valid specifiers for the `workspace:` protocol. We currently support `workspace:1.2.3`, `workspace:*`, [`workspace:bar@*`](https://pnpm.io/workspaces#referencing-workspace-packages-through-aliases), `workspace:../path/to/package`.

### Testing Instructions

Added unit tests for the case of a dependency of the form `"foo": "workspace:../bar"` where `foo` is another workspace package.

Verified fix works with repro provided in: https://github.com/vercel/turbo/issues/6744

### CODE REVIEW

File: crates/turborepo-repository/src/package_graph/dep_splitter.rs [hunk 1]
```diff
@@ -62,17 +78,21 @@ impl<'a> DependencySplitter<'a> {
...
-        if version == "*" || version == "^" || version == "~" {
-            Some(Self::Alias(name))
-        } else {
-            None
+        match version.rsplit_once('@') {
+            Some((name, "*")) | Some((name, "^")) | Some((name, "~")) => Some(Self::Alias(name)),
+            // No indication of different name for the package
+            // We want to capture specifiers that have type "directory" by npa which boils down to
+            // checking for slashes: https://github.com/pnpm/npm-package-arg/blob/main/npa.js#L79
+            Some(_) | None if version.contains('/') => {
```
Comment (NicholasLYang) [inline crates/turborepo-repository/src/package_graph/dep_splitter.rs:92]: The code linked above appears to check for backslashes on windows. Should we do that?

**Review by NicholasLYang — APPROVED** [review]
Just one question about windows, otherwise LGTM

File: crates/turborepo-repository/src/package_graph/dep_splitter.rs (hunk 1 above)
Comment (chris-olszewski) [reply crates/turborepo-repository/src/package_graph/dep_splitter.rs:92]: Luckily in this case pnpm does not generate `workspace:..\windows-path` and expects these to be unix style.

The npa code is used a lot of places, but luckily here we don't have to worry about the "is this path a system or unix style" question.
