### PR TITLE
fix: support prune without turbo.json

### LINKED ISSUE #3645: [turborepo] Regression - Using `turbo prune` was working without turbo.json, fails since 1.7.1
### What version of Turborepo are you using?

1.7.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I'm using `turbo prune` as part of my docker ci/cd flow, other than for `prune` a different build system is handling the test/lint/build flow, since turbo has support for pnpm workspace projects discovery no `turbo.json` was required.

# Working 1.7.0
Example for behavior in 1.7.0

```
(base) m@m-inspiron5567:~/code/allbetter/Core$ pnpm install turbo@1.7.0 --global    
Packages: +2 -2
++--
Progress: resolved 40, reused 31, downloaded 0, added 0, done

/home/m/.local/share/pnpm/global/5:
- turbo 1.7.1
+ turbo 1.7.0 (1.7.3 is available)

Done in 1.7s
(base) m@m-inspiron5567:~/code/allbetter/Core$ turbo prune --scope="better" --docker
╭──────────────────────────────────────────────────────────────────────╮
│                                                                      │
│                   Update available v1.7.0 ≫ v1.7.3                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.7.3    │
│                    Run "npm i -g turbo" to update                    │
│                                                                      │
│     Follow @turborepo for updates: https://twitter.com/turborepo     │
╰──────────────────────────────────────────────────────────────────────╯
Generating pruned monorepo for better in /home/m/code/allbetter/Core/out
 - Added better
 - Added better-config
 - Added middlewares
 - Added utils
```

# Failing 1.7.1
```
(base) m@m-inspiron5567:~/code/allbetter/Core$ pnpm install turbo@1.7.1 --global    
Packages: +2 -2
++--
Progress: resolved 40, reused 31, downloaded 0, added 0, done
.pnpm/turbo@1.7.1/node_modules/turbo: Running postinstall script, done in 79ms

/home/m/.local/share/pnpm/global/5:
- turbo 1.7.0
+ turbo 1.7.1 (1.7.3 is available)

Done in 2.2s
(base) m@m-inspiron5567:~/code/allbetter/Core$ turbo prune --scope="better" --docker
╭──────────────────────────────────────────────────────────────────────╮
│                                                                      │
│                   Update available v1.7.1 ≫ v1.7.3                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.7.3    │
│                    Run "npm i -g turbo" to update                    │
│                                                                      │
│     Follow @turborepo for updates: https://twitter.com/turborepo     │
╰──────────────────────────────────────────────────────────────────────╯
Generating pruned monorepo for better in /home/m/code/allbetter/Core/out
 - Added better
 - Added better-config
 - Added generator-app
 - Added middlewares
 - Added utils
 ERROR  failed to read turbo.json: Could not find turbo.json. Follow directions at https://turbo.build/repo/docs to create one: file does not exist
Turbo error: failed to read turbo.json: Could not find turbo.json. Follow directions at https://turbo.build/repo/docs to create one: file does not exist
```

### Expected Behavior

`turbo prune` should seccssfuly prepare the `out` directory.

### To Reproduce

1. Setup a pnpm workspace, 
2. Install turbo repo 1.7.1+ globally. 
3. Attempt to run `turbo prune`

### Reproduction Repo

_No response_

### PR DESCRIPTION
**Pull request by chris-olszewski**
Fixes #3645
Before #3216 we would ignore if `turbo.json` wasn't present. This PR restores that behavior by ignoring "not exists" errors.

Note: this is a slight UI change as we're now wrapping the not found error so we can match against it:
Previous:
` ERROR  failed to read turbo.json: Could not find turbo.json. Follow directions at https://turbo.build/repo/docs to create one: file does not exist`
New:
` ERROR  failed to read turbo.json: Could not find turbo.json. Follow directions at https://turbo.build/repo/docs to create one: Could not find turbo.json: file does not exist`

### CODE REVIEW

File: cli/internal/fs/turbo_json.go [hunk 1]
```diff
@@ -126,7 +126,7 @@ func LoadTurboConfig(rootPath turbopath.AbsoluteSystemPath, rootPackageJSON *Pac
 	if !includeSynthesizedFromRootPackageJSON && err != nil {
 		// If the file didn't exist, throw a custom error here instead of propagating
 		if errors.Is(err, os.ErrNotExist) {
-			return nil, fmt.Errorf("Could not find %s. Follow directions at https://turbo.build/repo/docs to create one: file does not exist", configFile)
+			return nil, errors.Wrapf(err, "Could not find %s. Follow directions at https://turbo.build/repo/docs to create one", configFile)
```
Comment (mehulkar) [inline cli/internal/fs/turbo_json.go:129]: Might want to rebase on `main` first. I think I did this in #2706 (smaller diff in #3760)
https://github.com/vercel/turbo/blob/5b44c9289e7d72f05745342ca7a1c6f63479bf0a/cli/internal/fs/turbo_json.go#L171

**Review by tknickman — APPROVED** [review]
